function [c,s]=givens(a,b)

%This file computes the entries in a 2x2 Givens rotation matrix
%generated by the entries a,b of a vector of length 2.
%theta = atan(-b/a);
%c=cos(theta);s=sin(theta);
c=a/sqrt(a^2+b^2);s=-b/sqrt(a^2+b^2);
end
%Do not write below this line.